# workflowの名前
name: Sample actions

# トリガーの設定
on:
  #suchedule:
  #  - cron: '00 18 * * *' # 1日一回起動
  push:
    branches: main # mainブランチの場合はmainに変更

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '103.0.5060.134'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install_library
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - shell: bash
        env:
          SECRET: ${{secrets.MISC}}
      - run: |
          python src/main.py